# Generated by Django 3.2.5 on 2021-07-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='houres',
            new_name='hours',
        ),
    ]
